FROM node:18

WORKDIR /app

# Installiere Abhängigkeiten
COPY  accessibility.test.package.json ./package.json
RUN npm install --only=dev

# Kopiere den Test-Code
COPY tests/ tests/

CMD ["npm", "test"]
