FROM node:18

# Kopiere den Test-Code
COPY ./tests /app/tests

WORKDIR /app

# Installiere Abhängigkeiten
COPY accessibility.test.package.json ./package.json
RUN npm install --only=dev

CMD ["npm", "test"]
